version: '3.8'

services:
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - shared-networks

networks:
  shared-networks:
    driver: bridge

volumes:
  postgres-data:
